steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/rxcalc-app/rxcalc-repo/rxcalc:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/rxcalc-app/rxcalc-repo/rxcalc:latest'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/rxcalc-app/rxcalc-repo/rxcalc:$BUILD_ID'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rxcalc'
      - 'us-central1-docker.pkg.dev/rxcalc-app/rxcalc-repo/rxcalc:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      '--allow-unauthenticated'
      - '--port=8080'
      '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300s'
      - '--concurrency=1000'
      - '--min-instances=0'
      '--max-instances=10'

# Configure the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitutionOption: 'ALLOW_LOOSE'

# Store images in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/rxcalc-app/rxcalc-repo/rxcalc:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/rxcalc-app/rxcalc-repo/rxcalc:latest'

# Substitutions
substitutions:
  _REGION: 'us-central1'